### ISSUE TITLE
Настройки viewport

### ISSUE THREAD

**Issue by tsivarev** [kuhel/vk-apps-boilerplate#1]
https://github.com/kuhel/vk-apps-boilerplate/blob/0079b76a8d7fa0d8f61dd10012420560cd664662/src/index.html#L6

<meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no, viewport-fit=cover">

**Comment by kuhel** [comment]
Fixed in https://github.com/kuhel/vk-apps-boilerplate/commit/caf92ba1d78b062369cb7d7f781d6b22f2cbb737
