### ISSUE TITLE
Нужно ли обязывать использовать SASS?

### ISSUE THREAD

**Issue by tsivarev** [kuhel/vk-apps-boilerplate#3]
https://github.com/kuhel/vk-apps-boilerplate/blob/0079b76a8d7fa0d8f61dd10012420560cd664662/src/style.scss#L1

Может назвать файл .css?

**Comment by kuhel** [comment]
Done in https://github.com/kuhel/vk-apps-boilerplate/commit/37f91dc0b8ce4909f1f11c09b14d4b3cc673b6e8
